### ISSUE TITLE
GetValue() method of Attribute types

### ISSUE THREAD

**Issue by tngranados** [getyoti/yoti-go-sdk#78]
I've had a problem last week in which I was trying to get the value of an attribute using the `GetValue` function that is exposed by it, but I was always getting nil as a result. Upon further inspection, I've seen that all attribute types are embedding the protobuf `Attribute` type which is the one exposing the `GetValue` method.
I know that the documentation always uses the attribute types `Value` method instead, but think it's weird and confusing to have a `GetValue` function that returns nil available as well, I made the mistake because it was suggested by my IDE and I didn't even think twice. Is there any reason to embed the protobuf `Attribute` type? Is not clear to me why you are doing that.

**Comment by echarrod** [comment]
Hi,

We originally chose to embed the `attribute` type because of the lack of supports of generics in Go: we need to be able to stored the representation of this inside each instance of our attributes. 

Having said this, I agree that it is confusing to have a `GetValue` method as well as a `Value` method, and it is something that we are also going to be addressing in the v3.0.0 major release to avoid this problem, by keeping all references to the protobuf Attribute internal and not available to clients.

If you "watch" the repo from https://github.com/getyoti/yoti-go-sdk/releases, you'll be automatically informed of new releases.

We'll keep this issue open until we have released the major.

Thanks

**Comment by echarrod** [comment]
Closing this, as it has been fixed in #84.

Please "watch" the repo from https://github.com/getyoti/yoti-go-sdk/releases to be notified when this will be released.
